application: myproject
version: 1-0-beta
runtime: go
api_version: go1

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /assets
  static_dir: assets

- url: /backend/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
